### ISSUE TITLE
Processing reference methylome

### ISSUE THREAD

**Issue by Qiuyu-dot** [alexpcheng/cfDNAme#2]
Hi Alex,

May i know how you deal with the reference methylome? From the paper on Med, you mentioned that you have downloaded the .bigWig data from the public resouces, such as ENCODE and Roadmap, as well as some other consortium under IHEC. I tried these datasets, but it seems that the methylation signals in the .bigWig files from different consortium are quite different. So, may i know how did you deal with these signals and integrate them together for DMR identification?

**Comment by alexpcheng** [comment]
Sorry I missed this! I did this the long way and normalized to a common format (bed) before processing.

**Comment by michael-kotliar** [comment]
Hi @alexpcheng, Do you have this reference methylome data somewhere available for download? It doesn't look like this repository includes it.
Thanks a lot!
